updated

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -20,25 +20,30 @@ jobs:
 
     steps:
 
-    # - name: Install boost
-    #   uses: MarkusJx/install-boost@v2.4.1
-    #   id: install-boost
-    #   with:
-    #     # REQUIRED: Specify the required boost version
-    #     # A list of supported versions can be found here:
-    #     # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
-    #     boost_version: 1.76.0
-    #     # OPTIONAL: Specify a platform version
-    #     # platform_version: 18.04
-    #     # OPTIONAL: Specify a custom install location
-    #     # boost_install_dir: /home/runner/some_directory
-    #     # OPTIONAL: Specify a toolset
-    #     # toolset: gcc
-    #     # OPTIONAL: Specify an architecture
-    #     # arch: x86
+    - name: Collect system infos
+    run: |
+      cat /etc/os-release
+      exit 1
 
-    #     # NOTE: If a boost version matching all requirements cannot be found,
-    #     # this build step will fail
+    - name: Install boost
+      uses: MarkusJx/install-boost@v2.4.1
+      id: install-boost
+      with:
+        # REQUIRED: Specify the required boost version
+        # A list of supported versions can be found here:
+        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
+        boost_version: 1.76.0
+        # OPTIONAL: Specify a platform version
+        # platform_version: 18.04
+        # OPTIONAL: Specify a custom install location
+        # boost_install_dir: /home/runner/some_directory
+        # OPTIONAL: Specify a toolset
+        # toolset: gcc
+        # OPTIONAL: Specify an architecture
+        # arch: x86
+
+        # NOTE: If a boost version matching all requirements cannot be found,
+        # this build step will fail
 
     - name: Install Ninja
       id: ninja
@@ -69,12 +74,12 @@ jobs:
         token: ${{ env.GITHUB_TOKEN }}
         # latest: true
 
-    - name: Install pre-requisites
-      run: |
-        sudo apt update
-        sudo apt upgrade -y
-        sudo apt install -y libboost-all-dev
-        # sudo apt install -y default-jdk libboost-all-dev lintian ninja-build
+    # - name: Install pre-requisites
+    #   run: |
+    #     sudo apt update
+    #     sudo apt upgrade -y
+    #     sudo apt install -y libboost-all-dev
+    #     # sudo apt install -y default-jdk libboost-all-dev lintian ninja-build
 
     # - name: Boost directories
     #   run: |
@@ -91,8 +96,8 @@ jobs:
         -DBoost_DEBUG=1
         # -DBoost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include \
         # -DBoost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib
-      # env:
-      #   BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
+      env:
+        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
 
     - name: Build executables
       run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
@@ -130,6 +135,8 @@ jobs:
     runs-on: macos-latest
 
     steps:
+    - name: suspended
+      run: exit 1
     - name: Collect system infos
       run: |
         system_profiler SPSoftwareDataType SPHardwareDataType
@@ -236,6 +243,8 @@ jobs:
     runs-on: windows-latest
 
     steps:
+    - name: suspended
+      run: exit 1
     - name: Install boost
       uses: MarkusJx/install-boost@v2.4.1
       id: install-boost
